services:
  _defaults:
    autowire: true

  ICanBoogie\HTTP\Responder:
    alias: ICanBoogie\HTTP\Responder\DelegateToProvider
    public: true

  ICanBoogie\HTTP\Responder\DelegateToProvider: ~

  ICanBoogie\HTTP\Responder\WithEvent:
    decorates: ICanBoogie\HTTP\Responder

  ICanBoogie\HTTP\Responder\WithRecovery:
    decorates: ICanBoogie\HTTP\Responder

  ICanBoogie\HTTP\ResponderProvider\Chain:
    arguments:
      - !tagged_iterator { tag: request_responder }

  ICanBoogie\HTTP\ResponderProvider:
    alias: ICanBoogie\HTTP\ResponderProvider\Chain
